//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OnePiece.Entities.Abstract;

namespace OnePiece.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character:IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Character()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int CharacterId { get; set; }
        public string CharacterName { get; set; }
        public string CharacterPower { get; set; }
        public int TayfaId { get; set; }
        public string MainPicture { get; set; }
    
        public virtual Tayfalar Tayfalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
