//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OnePiece.Entities.Abstract;

namespace OnePiece.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details : IEntity
    {
        public int OrderId { get; set; }
        public int CharacterId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> Quantity { get; set; }
        public string Discount { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Order Order { get; set; }
    }
}
